# Generated by Django 3.1.2 on 2020-10-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estado_mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_mascota', models.CharField(max_length=50)),
                ('historia_clinica', models.TextField(max_length=280)),
            ],
        ),
    ]
