# Generated by Django 3.1.2 on 2020-12-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0014_auto_20201130_2334'),
        ('veterinario', '0002_remove_estado_mascota_estado_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_mascota',
            name='r_historia_clinica',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estado_mascota',
            name='historia_clinica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_mascotas.mascota'),
        ),
    ]
