# Generated by Django 3.1.2 on 2020-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinario', '0003_auto_20201201_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_mascota',
            name='r_historia_clinica',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
