# Generated by Django 3.1.2 on 2020-12-01 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0014_auto_20201130_2334'),
        ('veterinario', '0004_auto_20201201_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_mascota',
            name='historia_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mascotas.mascota'),
        ),
    ]
