# Generated by Django 3.1.2 on 2020-12-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinario', '0008_auto_20201207_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_mascota',
            name='r_historia_clinica',
            field=models.CharField(max_length=500),
        ),
    ]
