# Generated by Django 3.1.2 on 2020-11-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0003_auto_20201106_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Perro', 'Perro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=20),
        ),
    ]
