# Generated by Django 3.1.2 on 2020-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0005_auto_20201114_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('En_custodia', 'En custodia'), ('En_tratamiento', 'En tratamiento'), ('En_adopcion', 'En adopción'), ('Adoptado', 'Adoptado')], max_length=20),
        ),
    ]
