# Generated by Django 3.1.2 on 2020-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0009_auto_20201115_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_rescate',
            field=models.DateTimeField(),
        ),
    ]
