# Generated by Django 3.1.2 on 2020-12-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0011_auto_20201117_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('En custodia', 'En custodia'), ('En tratamiento', 'En tratamiento'), ('En adopcion', 'En adopción'), ('Adoptado', 'Adoptado')], max_length=20),
        ),
    ]
