# Generated by Django 3.1.2 on 2020-12-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0013_auto_20201130_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_rescate',
            field=models.DateTimeField(null=True),
        ),
    ]
