# Generated by Django 3.1.2 on 2020-11-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_mascotas', '0002_auto_20201106_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil_adoptante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulo_familiar', models.IntegerField()),
                ('experiencia_mascotas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='perfil_adoptar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_adopcion', models.CharField(max_length=250)),
                ('descripcion_adopcion', models.TextField(max_length=280)),
                ('Mascota', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_mascotas.mascota')),
            ],
        ),
    ]
