# Generated by Django 3.1.2 on 2020-10-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0001_initial'),
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil_adoptante',
            old_name='persona',
            new_name='Persona',
        ),
        migrations.RemoveField(
            model_name='perfil_adoptar',
            name='mascota',
        ),
        migrations.AddField(
            model_name='perfil_adoptar',
            name='Mascota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_mascotas.mascota'),
        ),
    ]
