# Generated by Django 3.1.2 on 2021-01-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_adoptante',
            name='hijos',
            field=models.BooleanField(null=True),
        ),
    ]
