# Generated by Django 3.1.2 on 2021-01-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_usuarios', '0003_auto_20201127_1113'),
        ('adopcion', '0002_perfil_adoptante_hijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_adoptante',
            name='Profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_usuarios.profile'),
        ),
    ]
