# Generated by Django 3.1.2 on 2021-02-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_auto_20210131_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_adoptante',
            name='acepta_terminos',
            field=models.BooleanField(null=True),
        ),
    ]
