# Generated by Django 3.1.2 on 2021-02-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0005_perfil_adoptante_acepta_terminos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='alergia_mascota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='antes_mascotas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='casa_apartemento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='casa_propia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='espacio_mascota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='hijos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='lugar_seg_mascota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='mas_mascotas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='mascota_sola',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='presupuesto_mascotas',
            field=models.IntegerField(null=True),
        ),
    ]
