# Generated by Django 3.1.2 on 2021-02-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_auto_20210209_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='acepta_terminos',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='alergia_mascota',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='antes_mascotas',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='casa_apartemento',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='casa_propia',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='espacio_mascota',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='experiencia_mascotas',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')]),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='hijos',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='lugar_seg_mascota',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='mas_mascotas',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='mascota_sola',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='presupuesto_mascotas',
            field=models.IntegerField(choices=[('1', 'Sí'), ('2', 'No')], null=True),
        ),
    ]
