# Generated by Django 3.1.2 on 2021-02-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0007_auto_20210210_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='alergia_mascota',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='antes_mascotas',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='casa_apartemento',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='casa_propia',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='espacio_mascota',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='experiencia_mascotas',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')]),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='hijos',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='lugar_seg_mascota',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='mas_mascotas',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='mascota_sola',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='perfil_adoptante',
            name='presupuesto_mascotas',
            field=models.IntegerField(choices=[(1, 'Sí'), (2, 'No')], null=True),
        ),
    ]
